### PR TITLE
Regex fix

### PR DESCRIPTION
**Pull request by Mottie**
Update to work with ip-regex v3.0+.

### CODE REVIEW

**Comment by Mottie** [comment]
Hmm, yeah I couldn't get the tests to work with the make file using `$(BIN)`... as soon as I removed it the test worked.

```sh
test:
	eslint --color --quiet *.js
	ava
```

**Comment by silverwind** [comment]
Hmm, are you running this on the default Windows prompt? Maybe something specific to the version of `make` you have. I'd suggest running it in either a Cygwin, MSYS or WSL shell.

I think we can actually replace `$(BIN)/something` with `npx something` to run module binaries which ought to be more compatible, but it requires a recent version of npm, I think 5.2.0+.

**Comment by silverwind** [comment]
Changes look good, I'm a bit wary of the requirement of Node 8 as I'd like to support 6. I think this could actually work as the incompatible regex is only there for the non-exact export, right?

**Comment by Mottie** [comment]
> I think this could actually work as the incompatible regex is only there for the non-exact export, right?

Yeah, it should as long as the exact option is set to `true`. And, I don't think there'll be any problems from the [generic ip regexp](https://github.com/sindresorhus/ip-regex/blob/master/index.js#L22-L24) since it's a separate function with separate options.

**Comment by silverwind** [comment]
Actually I see that `ip-regex` defines 

````json
"engines": {
  "node": ">=8"
}
````
which I think means that installing this module on Node 6 will fail unless forced. 

I would still agree on bumping the required version, but for that to be worth it, I think we should transform both the non-exact and exact regexes to include the cidr part.

**Comment by Mottie** [comment]
Hmm, the boundary part of the regexp is complicated:

```js
const word = '[a-fA-F\\d:]';
const b = `(?:(?<=\\s|^)(?=${word})|(?<=${word})(?=\\s|$))`;
```
Mostly because the standard `\b` doesn't include a colon. So stripping those out may be a bit more complicated.

**Comment by silverwind** [comment]
Currently trying to insert the CIDR before the last capture group `(?=\s|$)`, might even work.

**Comment by Mottie** [comment]
What if we discussed this with sindresorhus... we could have the module include the raw `v4` and `v6` strings in the exports.

**Comment by silverwind** [comment]
Got it working in https://github.com/silverwind/cidr-regex/commit/14f2b4bcf01f3bdcf3b1538dd654460c95a5d40c.

**Pull request closed without merging**
